name: Angular-CLI

# Trigger
on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0
      # Setup nodeJS
    - name: Setup nodeJs
      uses: actions/setup-node@v4.0.4
      with:
        node-version: "20"
      # Install dependencies
    - name: Install deps
      run: npm i
      # Build app for production
    - name: Build app bundle
      run: npm run build
      # Deploy to GitHub pages
    - name: Deploy to pages
      uses: crazy-max/ghaction-github-pages@v4.0.0
      with:
        build_dir: dist/
        target_branch: gh-pages
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
